### ISSUE TITLE
Symfony support

### ISSUE THREAD

**Issue by stephanvierkant** [IsraelOrtuno/pipedrive#1]
I'm using Symfony and I think this repo would be easy to use with Symfony, but there are some small problems with it right now:

* The ``studly_case`` function doesn't exist.  (https://github.com/IsraelOrtuno/pipedrive/blob/master/src/Pipedrive.php#L54)
* No documentation how to use it w/ Symfony

Currently, I'm using [TTRGroup/pipedrive-api-php](https://github.com/TTRGroup/pipedrive-api-php), but it just a stub and it has [no active maintainer](https://github.com/TTRGroup/pipedrive-api-php/issues/17) right now.

**Comment by IsraelOrtuno** [comment]
Let me check it out

**Comment by IsraelOrtuno** [comment]
Last commit replaced that helper with the `Str::studly` method, can you please update and try now again?

Tests were passing anyways so not sure what could be happening as `helpers.php` from the `Illuminate\Support` package should be automatically included.

Do not really know how Symfony works, but you could use it in a traditional way:

```php
$pipedrive = new Devio\Pipedrive\Pipedrive('token');

$organizations = $pipedrive->organizations->all();
```

Docs are still not complete, will try to work on it this week.

**Comment by IsraelOrtuno** [comment]
By the way, this project is not specific for Laravel. It's completely Framework Agnostic. Just included an easier way for using with Laravel. Will definitely improve docs to leave everything clear :D

**Comment by stephanvierkant** [comment]
Thanks! I'm using it in one of my projects, so I'll try to improve your code + docs where I can.

**Comment by IsraelOrtuno** [comment]
Glad it's being helpful for you. Will love feedback ;D

**Comment by IsraelOrtuno** [comment]
Forgot to add a tag, it's being tagged now as `0.2.4`

**Comment by IsraelOrtuno** [comment]
Btw, docs have also been improved, hope it gets easier to work with :dancer:

**Comment by stephanvierkant** [comment]
I'm impressed by the docs, thanks!
