### ISSUE TITLE
Error: Wrong parameters for PipedriveException

### ISSUE THREAD

**Issue by borislt** [IsraelOrtuno/pipedrive#109]
Hey! 👋

I'm getting a strange error like this one:

`{"error":"Wrong parameters for Devio\\Pipedrive\\Exceptions\\PipedriveException([string $message [, long $code [, Throwable $previous = NULL]]])","file":"/app/vendor/devio/pipedrive/src/Http/Request.php:92"}`

Getting it from time to time. Looks like some kind of unforeseen response from Pipedrive API is triggering it.
Unfortunately, I don't have any idea how to reproduce it.

Have you encountered something like that?

**Comment by IsraelOrtuno** [comment]
Closed by #108
