### ISSUE TITLE
Verbose info for logging exception reasons

### ISSUE THREAD

**Issue by profluck** [IsraelOrtuno/pipedrive#117]
HI :)
![pipedrive-issue](https://user-images.githubusercontent.com/20466588/141444821-c0b8928f-9301-4a23-ac8e-8ac09f6d746c.png)
![pipedrive-issue-2](https://user-images.githubusercontent.com/20466588/141446193-00491893-610a-4264-a628-462fd687cefb.png)

It would be great to show an additional reason for the error for quick debugging. Thanks

**Comment by IsraelOrtuno** [comment]
You are right but this seems like a breaking change. What's your proposal?

**Comment by profluck** [comment]
As a quick solution concatenate error message with additional error info.
Official PipeDrive link on it: https://pipedrive.readme.io/docs/core-api-concepts-responses

```php
/**
* Throws PipedriveException with message depending on content.
* @see https://pipedrive.readme.io/docs/core-api-concepts-responses
*
* @param \stdClass $content
*/
protected function throwPipedriveException($content)
{
    if (!isset($content->error, $content->error_info)) {
        throw new PipedriveException('Error unknown.');
    }

    $errorMessage = $content->error . '. Info: ' . $content->error_info;

    throw new PipedriveException($errorMessage);
}
```
