### ISSUE TITLE
Removal of follower_count updates in Webhooks December 6, 2021

### ISSUE THREAD

**Issue by zinomorf** [IsraelOrtuno/pipedrive#118]
Removal of follower_count updates in Webhooks
What is changing?

The following types of Webhooks will no longer be triggered when a follower is added or removed:

updated.deal
updated.person
updated.organization
updated.product
Previously, when a follower was added or removed, a webhook was triggered with new update_time and follower_count values for the entity.

Published on December 6, 2021
https://pipedrive.readme.io/docs/changelog 

How will these changes be reflected in the work?
Is there an alternative functionality?

**Comment by IsraelOrtuno** [comment]
This package does not contain any model of what's being returned from Pipedrive's API nor handles webhook calls so I think this does not affect.
