### ISSUE TITLE
Is there any way to filter the records

### ISSUE THREAD

**Issue by jagroop** [IsraelOrtuno/pipedrive#12]
i mean that would be nice if we can get desired records from the pipeline

for example in case if i want to fetch deals in asc or desc order

please let me know if there is a way

Thanks !

**Comment by IsraelOrtuno** [comment]
Yes, when fetching deals just pass the `sort` key to the options array and they will be sorted as you like. It's included in the API docs 👍  

```
sort	
string	
Field names and sorting mode separated by comma (field_name_1 ASC, field_name_2 DESC). Only first-level field keys are supported (no nested keys).
```

**Comment by IsraelOrtuno** [comment]
I have been testing this: 

```
$pipedrive->deals->all(['sort' => 'name ASC']);
```

It should work, but it looks like there is an error on the Pipedrive side as it's responding:

```
Internal Server Error occurred. Pipedrive staff was notified about this.
```

**Comment by IsraelOrtuno** [comment]
Ok doing a bit more of testing I realised it's working pretty well, I was using `name` and we should use `title` in this case... Pipedrive sorts only for deal property, no for nested elements so this works perfect:

```
$deals = $pipedrive->deals->all(['sort' => 'value ASC']);

foreach ($deals->getData() as $deal)
{
    echo "{$deal->value} <br/>";
}
```

This works like a charm 💃
