### ISSUE TITLE
Lists e-mail messages associated with a deal.

### ISSUE THREAD

**Issue by jagroop** [IsraelOrtuno/pipedrive#13]
Hi there,
Does this php binding provide email messages associated with a deal
i have tried two ways

`Pipedrive::deals()->emailMessages($dealId);`

`Pipedrive::deals()->find(3)->emailMessages();`

but no success ...

**Comment by IsraelOrtuno** [comment]
@jagroop have just fixed this, this method was missing from the deals resource. Use it as you do:

```php
Pipedrive::deals()->emailMessages($dealId);
// or
Pipedrive::deals->emailMessages($dealId);
```

**Comment by IsraelOrtuno** [comment]
@jagroop tagged as 0.3.3 by the way, update composer

**Comment by jagroop** [comment]
composer update .. will update the binding version ?

**Comment by dominiquedutra** [comment]
Just for future reference, the correct method would be `->mailMessages()` instead of `->emailMessages()`.
