### ISSUE TITLE
Get activities from a deal

### ISSUE THREAD

**Issue by NielsKoole** [IsraelOrtuno/pipedrive#18]
Thank you for providing a really simple to use library for Pipedrive.

I'm struggling to get the activities from a deal (according to the docs: https://developers.pipedrive.com/docs/api/v1), I tried it this way:
`Pipedrive::deals()->find($dealId)->activities();`
But that doesn't work.

Is it possible and how should I do this?

**Comment by IsraelOrtuno** [comment]
It is a different method. Pipedrive does not include the activities in the response. You can use:
```
Pipedrive::deals()->activities($dealId);
```
