### ISSUE TITLE
In readme wrong example

### ISSUE THREAD

**Issue by dkulyk** [IsraelOrtuno/pipedrive#2]
In aliases config example **'Devio\Pipedrive\PipedriveFacade::class'**  must be as **Devio\Pipedrive\PipedriveFacade::class** without uotes

**Comment by IsraelOrtuno** [comment]
True, just changed it quickly. Will fix it later.

On Friday, 18 December 2015, Dmytro Kulyk <notifications@github.com> wrote:

> In aliases config example *'Devio\Pipedrive\PipedriveFacade::class' *
> must be as **Devio\Pipedrive\PipedriveFacade::class**
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/IsraelOrtuno/pipedrive/issues/2>.
>


-- 

Un saludo
Israel Ortuño
