### ISSUE TITLE
Persons::find() seems to only support id, functionality does not match documentation

### ISSUE THREAD

**Issue by ericcholis** [IsraelOrtuno/pipedrive#24]
https://developers.pipedrive.com/docs/api/v1/#!/Persons/get_persons_find

Sample request: 
`https://api.pipedrive.com/v1/persons/find?term=test%40test.com&start=0&search_by_email=1&api_token=ABC123`

**Comment by IsraelOrtuno** [comment]
The method you are looking for is `findByName`
