### ISSUE TITLE
Find with "term" and "by_email".

### ISSUE THREAD

**Issue by danielschweiger** [IsraelOrtuno/pipedrive#25]
With plain curl I use this URL:
...../persons/find/?api_token=xxx&term=email@domain.com&search_by_email=1

Is this implemented?

**Comment by IsraelOrtuno** [comment]
This is already implemented and its linked to this endpoint:

https://developers.pipedrive.com/docs/api/v1/#!/Persons/get_persons_find

Just use the `findByName($term, ['search_by_email' => true])` on a persons resource.

You can check it out here:

https://github.com/IsraelOrtuno/pipedrive/blob/master/src/Resources/Traits/FindsByName.php#L13-L18
