### ISSUE TITLE
Pagination with the all() function

### ISSUE THREAD

**Issue by zang** [IsraelOrtuno/pipedrive#29]
A quick question: Does the **all()** function return all the items even if there are thousands of them? If not, what's the best way to get the total number of the items for pagination purpose? 
thanks.

**Comment by IsraelOrtuno** [comment]
https://developers.pipedrive.com/docs/api/v1/#!/Deals/get_deals_find

Check this out and pass the necessary parameters, pagination is a matter of the API response.
