### ISSUE TITLE
File upload

### ISSUE THREAD

**Issue by stephanvierkant** [IsraelOrtuno/pipedrive#3]
I can't get the file upload working. I'm not sure it's an issue with the library, maybe I'm doing something wrong. If so, I'm sorry ;)

```
public function uploadFile($dealId, \SplFileInfo $file)
{
     $upload = $this->pipedrive->files->add([
        'file' => $file,
        'deal_id' => $dealId
    ]);
}
```

This throws a `PipedriveException`: 'No files were provided with the request.'. 

What's going wrong?

**Comment by IsraelOrtuno** [comment]
Let me have a look...

**Comment by IsraelOrtuno** [comment]
I am getting this error `You need to be authorized to make this request`, looks like it's a Pipedrive Error. Have just notified them, will get back to you.

**Comment by IsraelOrtuno** [comment]
Commit e8800a419afc0fe26fd3b2a4403a4120b2307082 should fix the issue, have to apologise, I did not implement this part. I have been playing and it should work... Tell you what you should do:

```php
$file = new \SplFileInfo('file.jpg');

$pipedrive->files->add([
    'file'   => $file,
    'person_id' => 1
]);
```

Will include this into the docs soon.

**Comment by stephanvierkant** [comment]
It's not working for me, unfortunately. I'm getting a 400 error from Pipedrive.

Info from Response:
content.error: An error occurred while saving the file.
content.error_info: Please check developers.pipedrive.com for more information about Pipedrive API.
content.data.error_code: unknown_error

**Comment by IsraelOrtuno** [comment]
What kind of file are you trying to save? I got that error when saving a `.php` file, but it was obvious.

**Comment by IsraelOrtuno** [comment]
Have just checked, I've got that error when uploading a `.md` file. However I have no problem uploading a `.jpg` file...

**Comment by stephanvierkant** [comment]
Even with PDF and JPG it's not working for me.

**Comment by IsraelOrtuno** [comment]
Could you email me one of those files to ai.ortuno at gmail.com?

**Comment by stephanvierkant** [comment]
Thanks, this time it was my fault. Thanks for helping!
