### ISSUE TITLE
List updates about a deal 

### ISSUE THREAD

**Issue by boudafc** [IsraelOrtuno/pipedrive#31]
Hello !
First, thank you for this beautiful work :)
However, I do not really understand regarding methods marked as implemented. I want to list all updates about a deal (flow function in pipedrive api) and it doesn't seems to exist.
Am I right ? or do I don't understand ?

thank you

**Comment by IsraelOrtuno** [comment]
It looks like I misunderstood that endpoint, fixing it :)

**Comment by IsraelOrtuno** [comment]
You should now be able to do:

```php
$pipedrive->deals->updates($id);
```

**Comment by IsraelOrtuno** [comment]
@boudafc can you confirm if this solved your issue? ;)

**Comment by boudafc** [comment]
Sorry I didn't see your answer. I have made a local trick by modifiying the deal class adding Flow function.  I'll test it (I'm on my smartphone) .

**Comment by boudafc** [comment]
It works like a charm.
However I'm wondering what kind of information provides "id/updates"

**Comment by IsraelOrtuno** [comment]
There is not endpoint for that in the API, was a mistake from my end ;)
