### ISSUE TITLE
Oauth Support

### ISSUE THREAD

**Issue by polyma** [IsraelOrtuno/pipedrive#37]
The new Pipedrive App Marketplace has switched over to oAuth authentication. Are there any plans for this package to support it?

**Comment by IsraelOrtuno** [comment]
Yes, will work on it when I get some time. Expect it soon :)

**Comment by IsraelOrtuno** [comment]
Could we discuss here how this should be implemented? cc @polyma @aakarim @daniti

I like the idea that @daniti suggested about handling token refreshing and all, but not sure how to deal with that as the refresh and access token should be stored somewhere:

- Some will store in a database table
- Others will cache it
- Others will include it into a users table column
- ... Infinite

**Comment by daniti** [comment]
One way could be to remain agnostic and let the user implement an interface with two endpoints (for example):

storeToken($user_id, $company_id, $pipedrive_oauth_token)
getStoredToken($user_id, $company_id) - returns PipedriveOAuthToken

Inside the two implemented methods you could do whatever you want: read/write from the session, encrypt, store in a db, etc.
And the library could still do all the "magic" of checking tokens and refreshing.

What do you think?

I still don't have an exact idea of the flow. Maybe you'd have to pass the implemented class as an argument in the construct... But I think you get the idea.

P.S. Also, we should remember to always use the combination of both user id and company id (user id is not enough to identify the user uniquely for Pipedrive)

**Comment by IsraelOrtuno** [comment]
Sure, the plan is to remain agnostic. That sounds like a plan! I like that.

The only thing the user will have to implement is that class with `get` and `set` methods for fetching or storing the token. Sounds good to me. As you said, that class will have to be provided to the constructor. As of now, the constructor gets the API key, in this case, the constructor will receive this class as "credentials", so it's the same at the end.

That looks sorted. In the other hand, we have the OAuth redirect to Pipedrive to approve the application. I guess we can provide a kind of RedirectTo method as Socialite does and then store the first token from the `set` method of the class mentioned above.

For refreshing, I think the user will have to deal with when to perform the refreshing. We could implement a `refresh` method to handle the refreshing process itself.

**Comment by daniti** [comment]
Sounds good.

Not too sure about the refresh method though... I think it could also be handled silently within the class.

Expiry and refresh token could stay in the PipedriveOAuthToken class, and we could silently check
$pipedrive_oauth_token

**Comment by daniti** [comment]
hey @IsraelOrtuno , I just pushed OAuth support on my fork.
I think it works nicely, and it's **backward compatible**.

It can be instantiated like this
```php
$pipedrive = Pipedrive::OAuth([
    'clientId' => 'xxxxx',
    'clientSecret' => 'xxxxx',
    'redirectUrl' => 'xxxxx',
    'storageClass' => PipedriveTokenIO::class
]);
```
`PipedriveTokenIO` is the user's own implementation of the `PipedriveTokenStorage` interface, with the two `setToken` and `getToken` methods.

`setToken` accepts an instance of `PipedriveToken`, which has these attributes
```php
protected $access_token;
protected $expires_at; // expires AT, not IN (calculated as time() + expires_in, coming from Pipedrive
protected $refresh_token;
```
`PipedriveToken` **silently takes care of refreshing the token when needed**, and updates it through the `setToken` method.

`PipedriveClient` checks if the token is valid. If it's not (or it's not set yet), it calls `$pipedrive->OAuthRedirect();`. On the callback page, you can call `$pipedrive->authorize($_GET['code']);` to get the first token (also automatically stored through the `setToken` method).

TODO: 
- comments
- support for Guzzle < 6 (which should be quick to implement)
- better handling of the redirect (?)

You can have a look on my fork if you want, and if you like it I can send you a PR :)

**Comment by IsraelOrtuno** [comment]
Yeah sure! Could you submit a PR to the develop branch?

**Comment by daniti** [comment]
done!

**Comment by IsraelOrtuno** [comment]
#52
