### ISSUE TITLE
it would be nice to add a field mapping

### ISSUE THREAD

**Issue by dkulyk** [IsraelOrtuno/pipedrive#4]
The easiest way to work with fields, which have a normal name.
Something like:
```PHP
// Deals
$organizations = $pipedrive
    ->deals(['621eeebb0431f9fe252ca369b3dd2f8c'=>'custom'])
    ->update(1,['custom'=>'value']);
```

**Comment by IsraelOrtuno** [comment]
Humm... Could try to map custom fields and give them their labelled name in studly case or something like that :+1:

**Comment by IsraelOrtuno** [comment]
#5
