### ISSUE TITLE
How to find deal by org_id?

### ISSUE THREAD

**Issue by pelcomppl** [IsraelOrtuno/pipedrive#42]
Hi

in documentation (https://developers.pipedrive.com/docs/api/v1/#!/Deals/get_deals_find) it is possible to get deal by org_id.
How to do it with your library?
`Pipedrive::deals()->find(['org_id' => 122]);`
Not works.

**Comment by IsraelOrtuno** [comment]
To use that endpoint you have to use the `findByName` method:

```php
Pipedrive::deals()->find($term, ['org_id' => 122]);
```

**Comment by IsraelOrtuno** [comment]
You can also do it this way:

https://developers.pipedrive.com/docs/api/v1/#!/Organizations/get_organizations_id_deals

```php
Pipedrive::organizations()->deals($organizationId);
```
https://github.com/IsraelOrtuno/pipedrive/blob/master/src/Resources/Traits/ListsDeals.php#L14-L19
