### ISSUE TITLE
vanila php autoload

### ISSUE THREAD

**Issue by r4mst3r** [IsraelOrtuno/pipedrive#43]
Hi there,

Great work on your project. I am just using PHP, no composer nor larvel. How do I autoload your files? trying to create instance of Pipedrive using below code but obviously it is throwing errors:

require_once('devio/pipedrive/pipedrive.php');
use Devio\Pipedrive;

$pd = new Pipedrive( "******" );

im getting errors of not finding class: Class 'Devio\Pipedrive'

**Comment by IsraelOrtuno** [comment]
This library requires other libraries such as Guzzle or others to make it work. You will need composer. If you do not want to use it, create a new composer project, require this package as dependence and include all the files into your project.
