### ISSUE TITLE
Better/strict typehinting?

### ISSUE THREAD

**Issue by JanMikes** [IsraelOrtuno/pipedrive#48]
Hello there!

I just started using this library - everything works as expected, thought i have a bit pain with typehinting methods, so my IDE understands return types, like this:

<img width="736" alt="screenshot 2018-09-25 17 23 45" src="https://user-images.githubusercontent.com/3995003/46024872-f5494c00-c0e7-11e8-9d2a-3aca96e74544.png">

As you can see from screenshot, it is not good programmer experience in code like that.

Is there any chance, this will get improved?

**Comment by JanMikes** [comment]
One more hint, using magic methods like this makes package almost impossible to test with static analysis, etc phpstan - http://github.com/phpstan/phpstan which can prevent many bugs in code

**Comment by IsraelOrtuno** [comment]
I understand what you say, but tried to use DRY pattern in order to simplify the development and maintenance... Would be open to merge a PR with all resources with their methods tho..

**Comment by JanMikes** [comment]
Hi @IsraelOrtuno and what about adding `@method` annotations? like this:
```php
/**
 * @method Activities activities()
 * @method ActivityFieldslds activityFields()
 *  ..... and more
 */
class Pipedrive
```

It will allow IDE to autocomplete and better understand the code:
<img width="335" alt="screenshot 2018-09-25 21 08 04" src="https://user-images.githubusercontent.com/3995003/46036945-1c634600-c107-11e8-9901-492841dab3e5.png">

Mind if i prepare PR like this? 😉

**Comment by JanMikes** [comment]
Will be very happy for merging and tagging a version for composer 🌹
