### ISSUE TITLE
How can i create a new Deal ??

### ISSUE THREAD

**Issue by jagroop** [IsraelOrtuno/pipedrive#6]
Hello sir,
I am trying to create a new deal . but i am unable to find an appropriate method to add a new deal.
That would be nice if you can share a piece of code.
Thanks !

**Comment by IsraelOrtuno** [comment]
You just have to use the `add` method to any kind of resource which is able to "add" things:

```
$pipedrive->deals->add([...]);
```

And pass any data relevant to the deal (title and others). Check the pipedrive api docs to know what parameters you should pass when creating a deal.

**Comment by jagroop** [comment]
Thanks :+1:
