### ISSUE TITLE
Resource is a reserved class name

### ISSUE THREAD

**Issue by mastef** [IsraelOrtuno/pipedrive#60]
I'm getting an error on PHP 7 / HHVM, as Resource is now [a reserved name](http://php.net/manual/en/reserved.other-reserved-words.php).

`Fatal error: Uncaught Error: Cannot use '\\Devio\\Pipedrive\\Resources\\Basics\\Resource' as class name as it is reserved in vendor/devio/pipedrive/src/Resources/Pipelines.php`

Renaming the `Resource` class name to something else fixed this issue.

**Comment by mastef** [comment]
It seems to me that this is a common hhvm issue. Also running into `Fatal error: Uncaught Error: array_creation_expression is not allowed in write context` within the illuminate/support dependency `vendor/illuminate/support/Arr.php:388` which doesn't like `[$value, $key] = someMethod();` syntax, based on Laravel's changes, which are only compatible with PHP 7.1+

So currently this package is only compatible from PHP 7.1+ on based on the dependencies.

**Comment by IsraelOrtuno** [comment]
This last issue is due Illuminate/Support package 5.7+. This package should not be installed if you do not have PHP 7.1+ installed, right?

For the HHVM you could manually require Illuminate/Support 5.6 in your composer and should do the trick.

**Comment by IsraelOrtuno** [comment]
For the reserved name... I will consider changing it, but it may be a breaking change for all those which are extending the API using this class, will have to tag a major version.

Thanks for reporting :)
