### ISSUE TITLE
Proposal: Add event dispatcher

### ISSUE THREAD

**Issue by dkulyk** [IsraelOrtuno/pipedrive#7]
You can add event dispatcher:
```
$pipedrive->on('update', 'product', function($previous, $current, $meta) {
    //code here...
});
$pipedrive->clients->on('update', function($previous, $current, $meta) {
    //code here...
});
$pipedrive->deals->on('create', function($current, $meta){
    //code here...
});
$pipedrive->dispatch($eventJson);
```

**Comment by IsraelOrtuno** [comment]
Humm... Pipedrive also includes `Push notifications` where you can register and trigger all this events :D

**Comment by dkulyk** [comment]
Yes. But to make it easier to work with them, you can add an event manager, which will:
- Use mapping;
- Distribute event notifications when *.*;
- The callback function to return objects of a certain type;

**Comment by IsraelOrtuno** [comment]
Hum... Not really sure about this. Imagine you create an Organization through Pipedrive app, you have to set a push notification for acting on that event when you have also defined an event listener when creating from your app.

**Comment by dkulyk** [comment]
I can identify one-time event notifications for *. * And dispatch them in the application.

**Comment by IsraelOrtuno** [comment]
Implementing this will become too complex, this package is intended to simplify the API use :)
