### ISSUE TITLE
Support new search endpoints

### ISSUE THREAD

**Issue by jamesgraham** [IsraelOrtuno/pipedrive#82]
Current endpoints will be deprecated in March 31, 2021

https://pipedrive.readme.io/docs/new-search-api-migration-guide

**Comment by IsraelOrtuno** [comment]
Would you mind helping migrating with a PR? :D

**Comment by jamesgraham** [comment]
Sure, I'll get to it at some point but wanted to get a reminder in 👍

**Comment by tomb1n0** [comment]
Would be nice to have support for this - any plans to merge the open PR?

**Comment by IsraelOrtuno** [comment]
Just need to test it, will try to test it today
