### ISSUE TITLE
Any update on Leads & Subscription Endpoint? 

### ISSUE THREAD

**Issue by manshu** [IsraelOrtuno/pipedrive#86]
I was checking the API and found no resource for both the endpoints. Any plan on that yet?

- [x] Leads endpoint
- [ ] Subscription endpoint

**Comment by IsraelOrtuno** [comment]
Probably new endpoints, could you share the links?

**Comment by manshu** [comment]
[](https://developers.pipedrive.com/docs/api/v1/#!/Leads )

That's for leads. I can't seem to find Subscriptions yet.

**Comment by IsraelOrtuno** [comment]
Just got an email from Pipedrive itself, will implement it ASAP:

Hi Israel,

My name is Elina and I'm a Technical Writer in Pipedrive. I'm writing to let you know that we have released the support for Leads API with 11 new endpoints:

GET /leads
GET /leads/{id}
GET /leadLabels
GET /leadLabels/{id}
GET /leadSources
POST /leads
POST /leadLabels
DELETE /leads/{id}
DELETE /leadLabels/{id}
PATCH /leads/{id}
PATCH /leadLabels/{id}

It'd be great if you could consider adding the support of those endpoints also to your public PHP client for Pipedrive API. 

For any questions related to the new endpoints or how to work with them, I've also added our Lead Engineer for Leads, Jakub Kadlubiec, as a cc to this email. Don't hesitate to contact us if you have any questions or concerns.

**Comment by iammichiel** [comment]
Perhaps, Pipedrive itself could sponsor the work?

**Comment by IsraelOrtuno** [comment]
Will add subscriptions before the end of the week too

**Comment by felixjunghans** [comment]
Hi @IsraelOrtuno are there any updates regarding subscriptions?

**Comment by IsraelOrtuno** [comment]
@kg-bot could you update this file in your vendor by adding a third parameter: https://github.com/IsraelOrtuno/pipedrive/blob/master/src/Resources/Basics/Resource.php#L75

```php 
return $this->request->post('', $values, ['content-type' => 'application/json']);
```

And let me know if this works? I could quickly fix then!

**Comment by IsraelOrtuno** [comment]
Mmm not sure if this may be a breaking change for other endpoints

**Comment by IsraelOrtuno** [comment]
@kg-bot PR #101 will fix the issue

**Comment by simensen** [comment]
#101 was merged, but unclear what more needs to be done for subscriptions. It's possible I can help with that if I had more detail on what still needs to be done.

**Comment by mikebastarache** [comment]
I was wondering if there has been any head way in the new Subscription end points?  I haven't been able to locate them in the Master branch.
