### ISSUE TITLE
Supporting Laravel 8 version.

### ISSUE THREAD

**Issue by nesh-ua** [IsraelOrtuno/pipedrive#87]
Hi, Are you going support Laravel 8? Now there is a conflict with guzzlehttp/guzzle

**Comment by applyACS** [comment]
Have the same issue.

**Comment by IsraelOrtuno** [comment]
https://github.com/IsraelOrtuno/pipedrive/releases/tag/2.6.0

This should fix it, clear composer cache `composer clear-cache` and update!
