### ISSUE TITLE
missing options

### ISSUE THREAD

**Issue by danijelk** [IsraelOrtuno/pipedrive#89]
Would it be a good idea to use $options here instead of $fields as with find() to open up possibility to use 'start, exact_match and limit' from the api? https://developers.pipedrive.com/docs/api/v1/#!/Organizations/get_organizations_search

https://github.com/IsraelOrtuno/pipedrive/blob/28c46ce870430de448b884e1740d70fb9f9aaf80/src/Resources/Traits/Searches.php#L15

**Comment by IsraelOrtuno** [comment]
Do you mean a third `$options` parameter? Since changing fields now would be breaking change

**Comment by danijelk** [comment]
yes adding $fields = [], $options = [] would work.
Then nothing else would be needed inside the method.

**Comment by IsraelOrtuno** [comment]
There was also a bug since options was never declared and was passing that var to the request

**Comment by danijelk** [comment]
Correct, two fixes for one :) thanks for quick action.
