### ISSUE TITLE
Support for find endpoint on Persons

### ISSUE THREAD

**Issue by casconed** [IsraelOrtuno/pipedrive#9]
`Persons` has a `find` endpoint: `api.pipedrive.com/v1/persons/find` that allows a text search of name or email. The `find` endpoint in the generic `Resource` only allows find by id. Is there a way to call `Persons::find`?

**Comment by IsraelOrtuno** [comment]
You are right, that `find` method is not implemented. I am going to add it today.

The current `find` method will be replaced by `get` probably. Let me have a look and consider the impact and will get back to you after pushing.

**Comment by IsraelOrtuno** [comment]
There is a method called `findByName`. Is this what you are looking for?

@casconed

**Comment by IsraelOrtuno** [comment]
ping @casconed

**Comment by casconed** [comment]
I think that will work - I just need to verify that the `search_by_email` option is supported.

**Comment by casconed** [comment]
Works! Thanks!
