### ISSUE TITLE
PipedriveToken class constructor changes token values

### ISSUE THREAD

**Issue by ziimk** [IsraelOrtuno/pipedrive#95]
👋 A dev from Pipedrive here. We are working on changing the token format in the near future and came across an issue in this library during testing.

When `new PipedriveToken([...])` is called [here](https://github.com/IsraelOrtuno/pipedrive/blob/d28a8680aa8789f985d769296341aad597616bf6/src/Pipedrive.php#L260-L264) with values from Pipedrive's OAuth `/token` endpoint response then the values are run through `array_map('camel_case', ...)`.

**This will result in broken access/refresh tokens assigned to the class properties if the first symbol happens to be in upper case.**

For example, access token `Foo` will be transformed to `foo` and will obviously fail validation when used to fetch data from Pipedrive API.

The token format should be opaque to the clients so any kind of manipulation with the tokens is risky :)

I think the easiest fix is to just remove the [call to camel_case](https://github.com/IsraelOrtuno/pipedrive/blob/d28a8680aa8789f985d769296341aad597616bf6/src/PipedriveToken.php#L37). As it works only on the array values, I don't quite understand why it's there at all 🤔

**Comment by IsraelOrtuno** [comment]
@daniti since you implemented this part, would you mind to help here?

**Comment by daniti** [comment]
I think the idea was to affect the keys and not the values, to be able to instantiate it with snake case attributes (like the ones coming from the API response, but the implementation is clearly a mistake.

Removing this call shouldn't negatively affect anything, so I'll just make a PR with this line removed.

Thank you @ziimk

**Comment by IsraelOrtuno** [comment]
Fixed PR #97
