### ISSUE TITLE
Changes on API endpoints in March 2021

### ISSUE THREAD

**Issue by LeMajstor** [IsraelOrtuno/pipedrive#96]
Pipedrive developers team are going to change some endpoints, among them:

- [ ] GET /deals/find
- [ ] GET /persons/find
- [ ] GET /organizations/find
- [ ] GET /products/find
- [x] GET /searchResults
- [x] GET /searchResults/field

There's going to have some update to support these new changes?

**Comment by IsraelOrtuno** [comment]
Yeah sure, do you have more info about this update?

**Comment by LeMajstor** [comment]
Sure, here goes the link to [their documentation](https://pipedrive.readme.io/docs/new-search-api-migration-guide) explaining about the changes.

**Comment by noudard** [comment]
They provide a new endpoint itemSearch

**Comment by MCKLtech** [comment]
+1 on this issue. Are you accepting PRs? We may be able to help abit.

**Comment by IsraelOrtuno** [comment]
@MCKLtech I do accept, any help is appreciated

**Comment by simensen** [comment]
@IsraelOrtuno @MCKLtech The new endpoint for `/itemSearch` endpoint is supported by #100. Unclear if it supports *everything*, but I'm guessing it's all good to go? It doesn't address the new search endpoints for individual resources (deals, persons, etc), though.

**Comment by IsraelOrtuno** [comment]
It does not apply for deals, persons, organizations or products, those are still missing

**Comment by IsraelOrtuno** [comment]
Not sure if we could include them in this same class to prevent breaking changes in those classes

**Comment by MCKLtech** [comment]
As far as I'm aware itemSearch is the core functionality and everything else e.g. Deals, Persons is a wrapper of that.

The lazy part of me is wondering can we make the current (And soon to be deprecated) implementations compatible with itemSearch to avoid sudden breakages.

**Comment by ampkeegan** [comment]
Bringing this back up as it's eminent now. One thing I noticed is the FindByName trait says it is deprecated in your code, but the API documentation doesn't say it will be deprecated for the /Users endpoint.
